name: docker-build
description: "Docker Build"

inputs:
  push:
    description: "Push Docker Image"
  github-token:
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/setup-qemu-action@v3
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}
    - uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          GAP_VERSION=${{ github.ref_name }}
